server:
  port : 7600

spring:
  application:
    name : ms-common
  profiles:
    active: dev
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        service-id: ms-core-config
#        enabled: true
#      profile: ${spring.profiles.active}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  datasource:
    dynamic:
      master:
        username: root
        password: 123123
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.0.5:3306/sk_cloud?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        druid:
          initial-size: 3
          max-active: 8
          min-idle: 2
          max-wait: -1
          min-evictable-idle-time-millis: 30000
          max-evictable-idle-time-millis: 30000
          time-between-eviction-runs-millis: 0
          validation-query: select 1
          validation-query-timeout: -1
          test-on-borrow: false
          test-on-return: false
          test-while-idle: true
          pool-prepared-statements: true
          max-open-prepared-statements: 100
          filters: stat,wall
          share-prepared-statements: true
      slave:
        one:
          username: root
          password: 123123
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://192.168.0.5:3306/sk_cloud_v2?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          druid:
            initial-size: 3
            max-active: 8
            min-idle: 2
            max-wait: -1
            min-evictable-idle-time-millis: 30000
            max-evictable-idle-time-millis: 30000
            time-between-eviction-runs-millis: 0
            validation-query: select 1
            validation-query-timeout: -1
            test-on-borrow: false
            test-on-return: false
            test-while-idle: true
            pool-prepared-statements: true
            max-open-prepared-statements: 100
            filters: stat,wall
            share-prepared-statements: true

# 文件服务器
fdfs:
  file-host: http://123.206.94.20:9999/
  tracker-list:
    - 123.206.94.20:22122


#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.ski.ms.common.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

---
spring:
  profiles: dev
eureka:
  instance:
     prefer-ip-address: true
     lease-renewal-interval-in-seconds: 5
     lease-expiration-duration-in-seconds: 20
  client:
     serviceUrl:
        defaultZone: http://sk:sk172839456@localhost:7100/eureka
     registry-fetch-interval-seconds: 10
