server:
  port: 7400

spring:
  application:
    name: ms-core-message-queue
  profiles:
    active: dev
  cloud:
    config:
      fail-fast: true
      discovery:
        service-id: ms-core-config
        enabled: true
      profile: ${spring.profiles.active}
      label: ${spring.profiles.active}
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

sms:
  aliyun:
    accessKey: accessKey
    secretKey: secretKey
    channels:
      loginCodeChannel: SMS_34630023

---
spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://sk:sk172839456@localhost:7100/eureka
    registry-fetch-interval-seconds: 10